backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "images"

collections: # A list of collections the CMS should be able to edit
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog" # Used in the UI, ie.: "New Post"
    folder: "source/blog" # The path to the folder where the documents are stored
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "html.markdown"
    create: true # Allow users to create new documents in this collection
    format: "yaml-frontmatter"
    frontmatter-delimiter: "---"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm UTC"}
      - {label: "Published", name: "published", widget: "boolean", default: false}
      - label: "Tags"
        name: "tags"
        widget: "list"
        fields:
          - {label: Tag, name: tag, widget: "string"}
